apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: kataokaap5
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      serviceAccountName: aws-load-balancer-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 095817875435.dkr.ecr.ap-northeast-1.amazonaws.com/kataokaecr5:latest
        ports:
        - name: http
          containerPort: 80
    
